### ISSUE TITLE
Cannot get code

### ISSUE THREAD

**Issue by cdugeai** [lobre/rmuploader#5]
This is not strictly linked to your software, but **I can't get anymore a code** from [https://my.remarkable.com/connect/remarkable](https://my.remarkable.com/connect/remarkable) (see screenshot). 

I think that it does not work anymore since Remarkable launched its [*commercial Connect feature*](https://remarkable.com/store/connect).

Can you still get a code from the url ? It used to work in the past, but now I have this blank page: 

![image](https://user-images.githubusercontent.com/46027833/142515839-b38ee09c-6840-4e50-aaff-4ef0df5004fa.png)

Thanks

**Comment by FlxSaenger** [comment]
This url works for me: https://my.remarkable.com/device/browser/connect

**Comment by cdugeai** [comment]
Yes, this is the link I was missing, thanks
